from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.layers.experimental.preprocessing import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam
from tensorflow.keras.models import load_model


class RandomModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # very similar to transfered_model.py, the only difference is that you should randomize the weights
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # randomize the weights of the loaded model, possibly by using _randomize_layers
        # use this model by removing the last layer, adding dense layers and an output layer
        # load the SAME architecture as your trained model
        base_model = load_model('results/best_model_epoch_11.keras')

        # wipe out the learned weights with fresh random ones
        self._randomize_layers(base_model)

        # freeze it, same as the transfer version, for a fair comparison
        for layer in base_model.layers:
            layer.trainable = False

        x = base_model.get_layer('flatten').output
        x = layers.BatchNormalization()(x)
        
        x = layers.Dense(64, activation='relu',name='transfer_dense_1')(x)
        output = layers.Dense(categories_count, activation='softmax',name='transfer_output')(x)

        self.model = models.Model(inputs=base_model.input, outputs=output)
    
    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
        self.model.compile(
            optimizer=Adam(learning_rate=0.0001),
            loss='categorical_crossentropy',
            metrics=['accuracy'],
        )


    @staticmethod
    def _randomize_layers(model):
        # Your code goes here

        # you can write a function here to set the weights to a random value
        # use this function in _define_model to randomize the weights of your loaded model
        pass
        for layer in model.layers:
            if hasattr(layer, 'kernel') and layer.kernel is not None:
                new_kernel = layer.kernel_initializer(shape=layer.kernel.shape)
                layer.kernel.assign(new_kernel)
            if hasattr(layer, 'bias') and layer.bias is not None:
                new_bias = layer.bias_initializer(shape=layer.bias.shape)
                layer.bias.assign(new_bias)

