from models.model import Model
from tensorflow.keras import Sequential, layers, models
from tensorflow.keras.layers.experimental.preprocessing import Rescaling
from tensorflow.keras.optimizers import RMSprop, Adam
from tensorflow.keras.models import load_model

class TransferedModel(Model):
    def _define_model(self, input_shape, categories_count):
        # Your code goes here
        # you have to initialize self.model to a keras model
        # load your basic model with keras's load_model function
        # freeze the weights of the loaded model to make sure the training doesn't affect them
        # (check the number of total params, trainable params and non-trainable params in your summary generated by train_transfer.py)
        # use this model by removing the last layer, adding dense layers and an output layer
        
        # load the best model
        base_model = load_model('results/best_model_epoch_11.keras')

        # freeze all of its layers so training doesn't touch them
        for layer in base_model.layers:
            layer.trainable = False

        # cut off the final softmax layer, keep everything before it
        x = base_model.get_layer('flatten').output
        x = layers.BatchNormalization()(x)

        # bolt on new trainable layers for the new task
        x = layers.Dense(64, activation='relu', name= 'transfer_dense_1')(x)
        output = layers.Dense(categories_count, activation='softmax', name='transfer_output')(x)

        self.model = models.Model(inputs=base_model.input, outputs=output)
    
    def _compile_model(self):
        # Your code goes here
        # you have to compile the keras model, similar to the example in the writeup
        self.model.compile(
            optimizer=Adam(learning_rate=0.0001),
            loss='categorical_crossentropy',
            metrics=['accuracy'],
        )
